// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Perch",
    platforms: [.macOS(.v15)],
    targets: [
        // Static Rust core + C module map, produced by scripts/build-xcframework.sh.
        .binaryTarget(name: "PerchCore", path: "Frameworks/PerchCore.xcframework"),
        // Generated by uniffi-bindgen-swift; regenerated on every framework build.
        .target(
            name: "PerchFFI",
            dependencies: ["PerchCore"],
            path: "Sources/PerchFFI",
            swiftSettings: [.swiftLanguageMode(.v5)]
        ),
        .executableTarget(
            name: "Perch",
            dependencies: ["PerchFFI"],
            path: "Sources/Perch",
            swiftSettings: [.swiftLanguageMode(.v6)]
        ),
    ]
)
