[package]
name = "perch-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "perch_ffi"
crate-type = ["staticlib", "cdylib", "lib"]

[dependencies]
perch-core = { path = "../perch-core" }
uniffi.workspace = true
thiserror.workspace = true
chrono.workspace = true

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[[bin]]
name = "uniffi-bindgen-swift"
path = "src/bin/uniffi-bindgen-swift.rs"

[dev-dependencies]
tempfile.workspace = true
